# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mburakow <mburakow@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/14 21:28:16 by mburakow          #+#    #+#              #
#    Updated: 2023/10/14 21:57:08 by mburakow         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SCRS = scrs/*.c

all:
	gcc $(SCRS) -o $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean re
